// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Products",
    "version": "1"
  },
  "paths": {},
  "definitions": {},
  "securityDefinitions": {},
  "host": "lz37ta80t6.execute-api.us-east-1.amazonaws.com/dev/",
  "schemes": [
    "https"
  ]
};