// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Products",
    "version": "1"
  },
  "paths": {
    "/import": {
      "get": {
        "summary": "importProductsFile",
        "description": "Returns a Signed URL for CSV file to import",
        "operationId": "importProductsFile.get./import",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Signed URL successfully generated"
          },
          "400": {
            "description": "Could not get signed URL"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "host": "lz37ta80t6.execute-api.us-east-1.amazonaws.com/dev/",
  "schemes": [
    "https"
  ]
};